[package]
name = "oneblock-rando"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anvil-region = "0.8"
hematite-nbt = "0.5.2"
serde = "1.0"
serde_json = "1.0"
serde_repr = "0.1"
structopt = "0.3"
